class Descriptions {
  static String title = "Welcome to Leebras Wealth";
  static String aboutUs =
      "Our company aims to make the dreams of those thousands and millions of people come true.\nWho over the years M.L.M.  Joined many companies in the sector with many dreams.  But every time they were disappointed because in whichever company they joined with their dreams, either that company itself was closed due to the greed and bad policy of their owners or it was the government's M.L.M.";
  static String title1 =
      "I am not a financial advisor nor any information given by me \nconstitutes professional advice.\nI am sharing my online experiences with the world.\nWhat you do with your money and time is your decision and \nyour responsibility.I am not responsible for any of your actions \nor non-actions and for your profit or loss arising out of it.\nPlease do your own research and use your own discretion \nbefore making any kind of investment\n*Note:- Direct selling is a risky and timely decision-making \nbusiness.  Please use your discretion before doing so.";
  static String wholeAboutUs =
      "Our company aims to make the dreams of those thousands and millions of people come true.  Who over the years M.L.M.  Joined many companies in the sector with many dreams.  \nBut every time they were disappointed because in whichever company they joined with their dreams, either that company itself was closed due to the greed and bad policy of their owners or it was the government's M.L.M.  \nDue to not being able to follow the guidelines made for the sector, it was closed.  Due to which the dreams of thousands of millions of people got shattered.Many people got out of this industry after mistaking this beautiful industry for this reason and buried their dreams there and either started their old business or left this world by saying goodbye.\nFriends this is M.L.M.  The industry in the sector is not bad.Evil are those people who come to this industry with their evil intentions by taking the help of this industry and come here and run away fulfilling their selfishness by misleading and deceiving the innocent people.Guys they are bad people! this industry is not bad.This industry is so beautiful that if a poor man can be made a millionaire-crorepati, then he is only and only M.L.M.  Industries only.\nTo live up to these hopes and aspirations, \nWe bring to you \"Libras Health & Wealth Care\" which will help you to make your dreams come true. Because the management team of this company believes in selfless and fair work.  The aim of this company is to give you good income along with health.We are working with the resolve to make the dreams of thousands of millions of people come true. Those who have been working continuously in this industry for many years with a faith in their heart to become Lakhpati Crorepati.So come on, your wait is over, success is waiting for you with wide arms.Libra has brought a gift of happiness at your doorstep. Do not miss this opportunity, come join hands.We will help you make your dreams come true";
  static String title2 =
      "Never get discouraged by constant failures because sometimes \nthe last key in the bunch opens the lock";
}
